name: main
on: [push]
jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup environment
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: yarn
      - name: Check types
        run: yarn typescript
      - name: Run lint
        run: yarn lint
      - name: Run test
        run: yarn test
